sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mahee1989/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mahee1989/docker-react npm run test
